{
 "title": "Bip Health Data (via Gadgetbridge)",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Total Steps",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT sum(\"steps\") AS \"total_steps\" FROM \"telegraf\".\"autogen\".\"gadgetbridge\" WHERE  $timeFilter"
    }
   ]
  },
  {
   "title": "Mean Steps/hr",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"total_steps\") FROM (SELECT sum(\"steps\") AS \"total_steps\" FROM \"telegraf\".\"autogen\".\"gadgetbridge\" WHERE  $timeFilter group by time(1h))"
    }
   ]
  },
  {
   "title": "Mean Heart Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"heart_rate\") AS \"mean_heart_rate\" FROM \"telegraf\".\"autogen\".\"gadgetbridge\" WHERE heart_rate < 254 and $timeFilter"
    }
   ]
  },
  {
   "title": "Max Heart Rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 0 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT max(\"heart_rate\") AS \"mean_heart_rate\" FROM \"telegraf\".\"autogen\".\"gadgetbridge\" WHERE heart_rate < 254 and $timeFilter"
    }
   ]
  },
  {
   "title": "PAI Score",
   "type": "stat",
   "description": "Current Personal Activity Intelligence (PAI) score - https://www.ntnu.edu/cerg/personal-activity-intelligence",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"pai_total\") AS \"PAI\" FROM \"telegraf\".\"autogen\".\"gadgetbridge\" WHERE  $timeFilter"
    }
   ]
  },
  {
   "title": "PAI Earned Today",
   "type": "stat",
   "description": "Personal Activity Intelligence (PAI) score points earned today - https://www.ntnu.edu/cerg/personal-activity-intelligence",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT last(\"pai_today\") AS \"PAI\" FROM \"telegraf\".\"autogen\".\"gadgetbridge\" WHERE  $timeFilter"
    }
   ]
  },
  {
   "title": "Average Activity Intensity",
   "type": "stat",
   "description": "The average intensity score for activities.\n\nThere's an explanation of the score meanings at https://support.zepp.com/en/faq/153",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"intensity\") AS \"intensity\" FROM \"telegraf\".\"autogen\".\"gadgetbridge\" WHERE  $timeFilter"
    }
   ]
  },
  {
   "title": "Max Activity Intensity",
   "type": "stat",
   "description": "The average intensity score for activities.\n\nThere's an explanation of the score meanings at https://support.zepp.com/en/faq/153",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 4 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT max(\"intensity\") AS \"intensity\" FROM \"telegraf\".\"autogen\".\"gadgetbridge\" WHERE  $timeFilter"
    }
   ]
  },
  {
   "title": "Steps",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 8 },
   "targets": [
    {
     "query": "SELECT sum(\"steps\") AS \"total_steps\" FROM \"telegraf\".\"autogen\".\"gadgetbridge\" WHERE  $timeFilter group by time($interval)"
    }
   ]
  },
  {
   "title": "Heart Rate and Activity Intensity",
   "type": "timeseries",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 8 },
   "targets": [
    {
     "query": "SELECT max(\"heart_rate\") AS \"max_heart_rate\" FROM \"telegraf\".\"autogen\".\"gadgetbridge\" WHERE heart_rate < 254 and $timeFilter group by time($interval)"
    },
    {
     "query": "SELECT mean(\"intensity\") AS \"Activity Intensity\" FROM \"telegraf\".\"autogen\".\"gadgetbridge\" WHERE  $timeFilter group by time($interval)"
    }
   ]
  },
  {
   "title": "Average Stress Score",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"stress\") AS \"stress\" FROM \"telegraf\".\"autogen\".\"gadgetbridge\" WHERE  $timeFilter"
    }
   ]
  },
  {
   "title": "Max Stress Score",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT max(\"stress\") AS \"stress\" FROM \"telegraf\".\"autogen\".\"gadgetbridge\" WHERE  $timeFilter"
    }
   ]
  },
  {
   "title": "Mean Stress Score Exc. Sleeping Hours",
   "type": "stat",
   "description": "The average stress score outside of configured sleeping hours",
   "gridPos": { "h": 4, "w": 6, "x": 12, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"stress_exc_sleep\") AS \"stress\" FROM \"telegraf\".\"autogen\".\"gadgetbridge\" WHERE  $timeFilter\n"
    }
   ]
  },
  {
   "title": "Max Stress Score Exc. Sleeping Hours",
   "type": "stat",
   "description": "The average stress score outside of configured sleeping hours",
   "gridPos": { "h": 4, "w": 6, "x": 18, "y": 16 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT max(\"stress_exc_sleep\") AS \"stress\" FROM \"telegraf\".\"autogen\".\"gadgetbridge\" WHERE  $timeFilter\n"
    }
   ]
  },
  {
   "title": "Average Stress Score",
   "type": "timeseries",
   "gridPos": { "h": 7, "w": 12, "x": 0, "y": 20 },
   "targets": [
    {
     "query": "SELECT mean(\"stress\") AS \"stress\" FROM \"telegraf\".\"autogen\".\"gadgetbridge\" WHERE  $timeFilter group by time($interval)"
    }
   ]
  },
  {
   "title": "Mean Daily Stress Score Exc. Sleeping Hours",
   "type": "stat",
   "description": "The average stress score outside of configured sleeping hours",
   "gridPos": { "h": 7, "w": 12, "x": 12, "y": 20 },
   "options": { "reduceOptions": { "calcs": [ "lastNotNull" ] } },
   "targets": [
    {
     "query": "SELECT mean(\"stress_exc_sleep\") AS \"stress\" FROM \"telegraf\".\"autogen\".\"gadgetbridge\" WHERE  $timeFilter group by time(1d)\n"
    }
   ]
  }
 ]
}